/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Cargo;
import Classes.Funcionarios;
import Classes.Indereco;
import Controller_Class_Entidades_Erp.Middle_BD_Funcionario;
import MysqlConectClasses.MyConectBD;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class Cadastrar_Funcionarios extends javax.swing.JFrame {

    int id;

    /**
     * Creates new form Cadastrar_Funcionarios
     */
    public Cadastrar_Funcionarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Lista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_Funcionario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNome_funcionario = new javax.swing.JTextField();
        Txt_telefone_funcionario = new javax.swing.JTextField();
        TxtData_inicio_funcao = new javax.swing.JTextField();
        BtnActualizar = new javax.swing.JButton();
        BtnNovo = new javax.swing.JButton();
        BtnApagar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Txtgenero_funcionario = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        minimizar = new javax.swing.JLabel();
        Sair = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jtable_Funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID FUNCIONÁRIO", "NOME FUNCIONÁRIO", "TELEFONE", "GÊNERO", "INÍÇIO DE FUNÇÃO"
            }
        ));
        Jtable_Funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_FuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_Funcionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 880, 190));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel2.setText("TELEFONE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel3.setText("DATA INICIO FUNCÃO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        TxtNome_funcionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtNome_funcionario.setForeground(new java.awt.Color(204, 204, 204));
        TxtNome_funcionario.setText("Nome do Funcionario");
        TxtNome_funcionario.setBorder(null);
        jPanel1.add(TxtNome_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 206, -1));

        Txt_telefone_funcionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Txt_telefone_funcionario.setForeground(new java.awt.Color(204, 204, 204));
        Txt_telefone_funcionario.setText("Telefone");
        Txt_telefone_funcionario.setBorder(null);
        jPanel1.add(Txt_telefone_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 206, -1));

        TxtData_inicio_funcao.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtData_inicio_funcao.setForeground(new java.awt.Color(204, 204, 204));
        TxtData_inicio_funcao.setText("Data inicio de função");
        TxtData_inicio_funcao.setBorder(null);
        jPanel1.add(TxtData_inicio_funcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 206, -1));

        BtnActualizar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BtnActualizar.setText("ACTUALIZAR");
        BtnActualizar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        BtnNovo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BtnNovo.setText("NOVO");
        BtnNovo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(BtnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        BtnApagar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BtnApagar.setText("APAGAR");
        BtnApagar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApagarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        BtnSalvar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BtnSalvar.setText("SALVAR");
        BtnSalvar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 210, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("ÁREA DE AUTENTICAÇÃO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 250, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel6.setText("NOME");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel9.setText("GÊNERO ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        Txtgenero_funcionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Txtgenero_funcionario.setForeground(new java.awt.Color(204, 204, 204));
        Txtgenero_funcionario.setText("Insira o gênero");
        Txtgenero_funcionario.setBorder(null);
        Txtgenero_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtgenero_funcionarioActionPerformed(evt);
            }
        });
        jPanel1.add(Txtgenero_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 206, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 210, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 340));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        minimizar.setText("Minimizar");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel2.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 20));

        Sair.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jPanel2.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 50, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ta.jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 180));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("MANTENHA-TE ACTUALIZADO");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 300, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // ADICIONAR DADOS NA BASE DE DADOS FUNCIONÁRIOS:
        Funcionarios funcionario = new Funcionarios();
        MyConectBD Connection = new MyConectBD();
        Middle_BD_Funcionario funcionarioBD = new Middle_BD_Funcionario();
        Indereco indereco = new Indereco();
        funcionario.setNome_funcionario(TxtNome_funcionario.getText());
        funcionario.setGenero_funcionario(Txtgenero_funcionario.getText());
        funcionario.setTelefone_funcionario(Integer.parseInt(Txt_telefone_funcionario.getText()));
        funcionario.setInicio_funcao(TxtData_inicio_funcao.getText());
        funcionarioBD.Inserir(funcionario);
        Lista();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void Jtable_FuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_FuncionarioMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) Jtable_Funcionario.getModel();
        Funcionarios funcionario = new Funcionarios();
        Middle_BD_Funcionario funcionarioBD = new Middle_BD_Funcionario();
        int id = (int) Jtable_Funcionario.getValueAt(Jtable_Funcionario.getSelectedRow(), 0);
        funcionario.setId_funcionario(id);
        // funcionarioBD.
        Lista();
    }//GEN-LAST:event_Jtable_FuncionarioMouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        Funcionarios funcionario = new Funcionarios();
        Middle_BD_Funcionario funcio = new Middle_BD_Funcionario();
        funcionario.setGenero_funcionario(Txtgenero_funcionario.getText());
        funcionario.setNome_funcionario(TxtNome_funcionario.getText());
        funcionario.setInicio_funcao(TxtData_inicio_funcao.getText());
        funcionario.setTelefone_funcionario(Integer.parseInt(Txt_telefone_funcionario.getText()));
        funcio.atualizar(funcionario);
        Lista();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnApagarActionPerformed

    private void Txtgenero_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtgenero_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtgenero_funcionarioActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0) {
            setVisible(false);
        }
    }//GEN-LAST:event_SairMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar_Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnApagar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTable Jtable_Funcionario;
    private javax.swing.JLabel Sair;
    private javax.swing.JTextField TxtData_inicio_funcao;
    private javax.swing.JTextField TxtNome_funcionario;
    private javax.swing.JTextField Txt_telefone_funcionario;
    private javax.swing.JTextField Txtgenero_funcionario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel minimizar;
    // End of variables declaration//GEN-END:variables

    private void Lista() {
        Middle_BD_Funcionario adicionador = new Middle_BD_Funcionario();
        DefaultTableModel Tabledata = (DefaultTableModel) Jtable_Funcionario.getModel();
        Tabledata.setNumRows(0);
        for (Funcionarios funcionario : adicionador.Listar()) {
            Object[] receberDados = {
                funcionario.getId_funcionario(),
                funcionario.getNome_funcionario(),
                funcionario.getGenero_funcionario(),
                funcionario.getTelefone_funcionario(),
                funcionario.getInicio_funcao(),};
            Tabledata.addRow(receberDados);
        }

    }
}
