/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller_Class_Entidades_Erp.Middle_CargoBD;
import MysqlConectClasses.MyConectBD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class Cargo extends javax.swing.JFrame {

    /**
     * Creates new form Cargo
     */
    public Cargo() {
        initComponents();
        this.setLocationRelativeTo(null);
        Adicionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TxtSalario = new javax.swing.JTextField();
        TxtCargo = new javax.swing.JTextField();
        TxtDesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCargo = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        sair = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtIdCargo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("SALÁRIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 20));

        jLabel2.setText("CARGO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 20));

        jLabel3.setText("DESCRIÇÃO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 20));

        jButton2.setText("NOVO");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 40, -1));

        jButton3.setText("SALVAR");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 50, -1));

        jButton4.setText("ACTUALIZAR");
        jButton4.setBorder(null);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 70, -1));

        jButton5.setText("APAGAR");
        jButton5.setBorder(null);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 50, -1));

        TxtSalario.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        TxtSalario.setForeground(new java.awt.Color(102, 102, 102));
        TxtSalario.setText("Informe o salário");
        TxtSalario.setBorder(null);
        jPanel1.add(TxtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        TxtCargo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        TxtCargo.setForeground(new java.awt.Color(102, 102, 102));
        TxtCargo.setText("Cargo Do funcionário");
        TxtCargo.setBorder(null);
        jPanel1.add(TxtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 180, 20));

        TxtDesc.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        TxtDesc.setForeground(new java.awt.Color(102, 102, 102));
        TxtDesc.setText("Descreve o Cagro");
        TxtDesc.setBorder(null);
        jPanel1.add(TxtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 180, -1));

        TbCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Cargo", "Cargo", "Descrição", "Salário"
            }
        ));
        TbCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbCargoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbCargo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 710, 150));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 180, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 180, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 180, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, 20));

        jTextField2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("Pesquisar Cargo");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 170, -1));

        sair.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jPanel1.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 40, 20));

        minimizar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        minimizar.setText("Minimizar");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 70, 20));

        jLabel6.setText("IDCARGO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 20));

        TxtIdCargo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        TxtIdCargo.setForeground(new java.awt.Color(102, 102, 102));
        TxtIdCargo.setText("Opcional");
        TxtIdCargo.setBorder(null);
        jPanel1.add(TxtIdCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 180, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        Classes.Cargo cargo = new Classes.Cargo();
        MyConectBD Connection = new MyConectBD();
        Middle_CargoBD cargoBD = new Middle_CargoBD();
        //cargo.setId_cargo(Integer.getInteger(TxtIdCargo.getText()));
        cargo.setDesc_cargo(TxtDesc.getText());
        cargo.setSalario(Double.parseDouble(TxtSalario.getText()));
        cargo.setCargo(TxtCargo.getText());
        cargoBD.AdicionarCargo(cargo);
        Adicionar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TbCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCargoMouseClicked
        // TODO add your handling code here:
          DefaultTableModel dtm = (DefaultTableModel) TbCargo.getModel();
        Classes.Cargo cargo = new Classes.Cargo();
        Middle_CargoBD cargoBD = new Middle_CargoBD();
        int id = (int)TbCargo.getValueAt(TbCargo.getSelectedRow(),0);
       cargo.setId_cargo(id);
        Adicionar();
    }//GEN-LAST:event_TbCargoMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
         int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0) {
             setVisible(false);
        }
    }//GEN-LAST:event_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbCargo;
    private javax.swing.JTextField TxtCargo;
    private javax.swing.JTextField TxtDesc;
    private javax.swing.JTextField TxtIdCargo;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel sair;
    // End of variables declaration//GEN-END:variables

    private void Adicionar() {
        Middle_CargoBD adicionador = new Middle_CargoBD();
        DefaultTableModel Tabledata = (DefaultTableModel) TbCargo.getModel();
        Tabledata.setNumRows(0);
        for (Classes.Cargo cargo : adicionador.ListarCargo()) {
            Object[] receberDados = {
                cargo.getId_cargo(),
                cargo.getCargo(),
                cargo.getDesc_cargo(),
                cargo.getSalario()
            };
            Tabledata.addRow(receberDados);
        }

    }

}
