/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Classes.Estudantes;
import Controller_Class_Entidades_Erp.Middle_BD_Estudante;
import MysqlConectClasses.MyConectBD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class Frm_Estudante extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Estudante
     */
    public Frm_Estudante() {
        initComponents();
        this.setLocationRelativeTo(null);
        Adicionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnSave = new javax.swing.JButton();
        BtnNovo = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnApagar = new javax.swing.JButton();
        CombIdCurso = new javax.swing.JComboBox();
        TxtTelef = new javax.swing.JTextField();
        TxtBusca = new javax.swing.JTextField();
        minimizar = new javax.swing.JLabel();
        sair = new javax.swing.JLabel();
        Txtgener = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbEstudantes = new javax.swing.JTable();
        TxtPlace = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        TxtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("BAIRRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("TELEFONE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("GÊNERO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 20));

        BtnSave.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        BtnSave.setText("SALVAR");
        BtnSave.setBorder(null);
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        BtnNovo.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        BtnNovo.setText("NOVO");
        BtnNovo.setBorder(null);
        jPanel1.add(BtnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        BtnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        BtnUpdate.setText("ACTUALIZAR");
        BtnUpdate.setBorder(null);
        jPanel1.add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        BtnApagar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        BtnApagar.setText("APAGAR");
        BtnApagar.setBorder(null);
        jPanel1.add(BtnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        CombIdCurso.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        CombIdCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID_CURSO" }));
        jPanel1.add(CombIdCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 127, -1));

        TxtTelef.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtTelef.setForeground(new java.awt.Color(102, 102, 102));
        TxtTelef.setText("Telefone ou Email");
        TxtTelef.setBorder(null);
        jPanel1.add(TxtTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 130, -1));

        TxtBusca.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtBusca.setForeground(new java.awt.Color(102, 102, 102));
        TxtBusca.setText("Pesquisar curso");
        TxtBusca.setBorder(null);
        TxtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 110, -1));

        minimizar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        minimizar.setText("Minimizar");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        sair.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jPanel1.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 33, -1));

        Txtgener.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Txtgener.setForeground(new java.awt.Color(102, 102, 102));
        Txtgener.setText("M F");
        Txtgener.setBorder(null);
        jPanel1.add(Txtgener, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 120, -1));

        TbEstudantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_ESTUDANTE", "NOME_ESTUDANTE", "CIDADE", "GÊNERO", "TELEFONE", "CURSO ", "PREÇO_CURSO", "Nº DA SALA"
            }
        ));
        TbEstudantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbEstudantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbEstudantes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 840, 172));

        TxtPlace.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtPlace.setForeground(new java.awt.Color(102, 102, 102));
        TxtPlace.setText("Localidade do Estudante");
        TxtPlace.setBorder(null);
        TxtPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPlaceActionPerformed(evt);
            }
        });
        jPanel1.add(TxtPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 210, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 180, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 210, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 210, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 210, 10));

        TxtNome.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtNome.setForeground(new java.awt.Color(102, 102, 102));
        TxtNome.setText("Nome Do Estudante");
        TxtNome.setBorder(null);
        TxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("NOME DO  ESTUDANTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        //  here:int dialog = JOptionPane.YES_NO_OPTION;
        int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_sairMouseClicked

    private void TxtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscaActionPerformed

    private void TxtPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPlaceActionPerformed

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        Estudantes estudante = new Estudantes();
        Middle_BD_Estudante estudanteBD = new Middle_BD_Estudante();
        MyConectBD Connection = new MyConectBD();
        estudante.setNomeEstudante(TxtNome.getText());
        estudante.setCidade(TxtPlace.getText());
        estudante.setTelefone(Integer.parseInt(TxtTelef.getText()));
        estudante.setGenero(Txtgener.getText());
        estudanteBD.Inserir(estudante);
        Adicionar();
        
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void TbEstudantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbEstudantesMouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel dtm = (DefaultTableModel)TbEstudantes.getModel();
         Estudantes estudante = new Estudantes();
        Middle_BD_Estudante estudanteBD = new Middle_BD_Estudante();
        int id = (int)TbEstudantes.getValueAt(TbEstudantes.getSelectedRow(),0);
        estudante.setIdestudante(id);
    }//GEN-LAST:event_TbEstudantesMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Estudante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApagar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox CombIdCurso;
    private javax.swing.JTable TbEstudantes;
    private javax.swing.JTextField TxtBusca;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtPlace;
    private javax.swing.JTextField TxtTelef;
    private javax.swing.JTextField Txtgener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel sair;
    // End of variables declaration//GEN-END:variables

private void Adicionar() {
        Middle_BD_Estudante adicionador = new Middle_BD_Estudante();
        DefaultTableModel Tabledata= (DefaultTableModel) TbEstudantes.getModel();
        Tabledata.setNumRows(0);
        for (Estudantes estudante : adicionador.ListarEstudante()) {
       Object[] receberDados={
          estudante.getIdestudante(),
           estudante.getNomeEstudante(),
           estudante.getCidade(),
           estudante.getGenero(),
           estudante.getTelefone()
       }; 
       Tabledata.addRow(receberDados);
        }
        
    }



}
