/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Professores;
import Controller_Class_Entidades_Erp.Middle_BD_Professor;
import static Controller_Class_Entidades_Erp.Middle_BD_Professor.stmt;
import MysqlConectClasses.MyConectBD;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class Frm_Professor extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Professor
     */
    public Frm_Professor() {
        initComponents();
        this.setLocationRelativeTo(null);
        Adicionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtCidade = new javax.swing.JTextField();
        TxtBegin = new javax.swing.JTextField();
        TxtTelefon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProfessor = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        TxtEspecialidade = new javax.swing.JTextField();
        TxtGen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        Busca = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Sair = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("NOME DO PROFESSOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("CIDADE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("TELEFONE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("DATA_INÍCIO_FUNCÃO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        TxtCidade.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtCidade.setForeground(new java.awt.Color(102, 102, 102));
        TxtCidade.setText("Localidade");
        TxtCidade.setBorder(null);
        jPanel1.add(TxtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 169, -1));

        TxtBegin.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtBegin.setForeground(new java.awt.Color(102, 102, 102));
        TxtBegin.setText("Início de Trabalho");
        TxtBegin.setBorder(null);
        TxtBegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBeginActionPerformed(evt);
            }
        });
        jPanel1.add(TxtBegin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 169, -1));

        TxtTelefon.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtTelefon.setForeground(new java.awt.Color(102, 102, 102));
        TxtTelefon.setText("Telefone");
        TxtTelefon.setBorder(null);
        jPanel1.add(TxtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 169, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("NOVO");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        BtnSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnSave.setText("SALVAR");
        BtnSave.setBorder(null);
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("ACTUALIZAR");
        jButton3.setBorder(null);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("APAGAR");
        jButton4.setBorder(null);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        TbProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_PROFESSOR", "NOME_PROFESSOR", "GÊNERO", "CIDADE", "ESPECIALIDADE", "TELEFONE", "INÍCIO DE FUNÇÃO"
            }
        ));
        TbProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbProfessorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbProfessor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 836, 125));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("ESPECIALIDADE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        TxtEspecialidade.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtEspecialidade.setForeground(new java.awt.Color(102, 102, 102));
        TxtEspecialidade.setText("Especialidade Académica");
        TxtEspecialidade.setBorder(null);
        jPanel1.add(TxtEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 169, -1));

        TxtGen.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtGen.setForeground(new java.awt.Color(102, 102, 102));
        TxtGen.setText("Género");
        TxtGen.setBorder(null);
        TxtGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGenActionPerformed(evt);
            }
        });
        jPanel1.add(TxtGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 169, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("GENERO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 20));

        TxtNome.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtNome.setForeground(new java.awt.Color(102, 102, 102));
        TxtNome.setText("Nome Do Professor");
        TxtNome.setBorder(null);
        jPanel1.add(TxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 169, -1));

        Busca.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Busca.setForeground(new java.awt.Color(102, 102, 102));
        Busca.setText("Pesquisar Professor");
        Busca.setBorder(null);
        jPanel1.add(Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 169, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 170, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 170, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 170, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 170, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 170, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 170, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 170, 10));

        Sair.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jPanel1.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 50, 20));

        Minimizar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Minimizar.setText("Minimizar");
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBeginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBeginActionPerformed

    private void TxtGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        Professores professor = new Professores();
        Middle_BD_Professor professorBD = new Middle_BD_Professor();
        MyConectBD conection = new MyConectBD();
        professor.setNome_professor(TxtNome.getText());
        professor.setGereno_professor(TxtGen.getText());
        professor.setEspecialidade_professor(TxtEspecialidade.getText());
        professor.setEndereco(TxtCidade.getText());
        professor.setTelefone(Integer.parseInt(TxtTelefon.getText()));
        professor.setInicio_funcao(TxtBegin.getText());
        professorBD.InserirProfessor(professor);
        Adicionar();
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void TbProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbProfessorMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) TbProfessor.getModel();
        Professores professor = new Professores();
        Middle_BD_Professor professorBD = new Middle_BD_Professor();
        int id = (int) TbProfessor.getValueAt(TbProfessor.getSelectedRow(), 0);
        professor.setId_professor(id);
        Adicionar();
    }//GEN-LAST:event_TbProfessorMouseClicked

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
              // TODO add your handling code here:
        int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0) {
             setVisible(false);
        }
    }//GEN-LAST:event_SairMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JTextField Busca;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel Sair;
    private javax.swing.JTable TbProfessor;
    private javax.swing.JTextField TxtBegin;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JTextField TxtEspecialidade;
    private javax.swing.JTextField TxtGen;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtTelefon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
private void Adicionar() {
        Middle_BD_Professor adicionador = new Middle_BD_Professor();
        DefaultTableModel Tabledata = (DefaultTableModel) TbProfessor.getModel();
        Tabledata.setNumRows(0);
        for (Professores professor : adicionador.ListarProfessor()) {
            Object[] receberDados = {
                professor.getId_professor(),
                professor.getNome_professor(),
                professor.getGereno_professor(),
                professor.getEndereco(),
                professor.getEspecialidade_professor(),
                professor.getTelefone(),
                professor.getInicio_funcao()
            };
            Tabledata.addRow(receberDados);
        }

    }

}
