/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Cursos;
import Controller_Class_Entidades_Erp.Middle_BD_Cursos;
import MysqlConectClasses.MyConectBD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class FrmCursos_Erp extends javax.swing.JFrame {

    /**
     * Creates new form FrmCursos_Erp
     */
    public FrmCursos_Erp() {
        initComponents();
        Adicionar();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sair = new javax.swing.JLabel();
        Pesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtCat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtDurabi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCursos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        TxtCurso1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sair.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jPanel1.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 30, -1));

        Pesquisa.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        Pesquisa.setForeground(new java.awt.Color(153, 153, 153));
        Pesquisa.setText("Pesquisar Curso");
        Pesquisa.setBorder(null);
        jPanel1.add(Pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 251, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("PREÇO DO CURSO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        TxtPreco.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        TxtPreco.setForeground(new java.awt.Color(153, 153, 153));
        TxtPreco.setText("Custo do Cruso");
        TxtPreco.setBorder(null);
        jPanel1.add(TxtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 251, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("DURAÇÃO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));

        TxtCat.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        TxtCat.setForeground(new java.awt.Color(153, 153, 153));
        TxtCat.setText("Técnico ou Teórico");
        TxtCat.setBorder(null);
        jPanel1.add(TxtCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 251, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("CATEGORIA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        TxtDurabi.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        TxtDurabi.setForeground(new java.awt.Color(153, 153, 153));
        TxtDurabi.setText("Tempo de Duração");
        TxtDurabi.setBorder(null);
        jPanel1.add(TxtDurabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 251, -1));

        jButton1.setText("SALVAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, 20));

        jButton2.setText("ACTUALIZAR");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 80, 20));

        jButton3.setText("APAGAR");
        jButton3.setBorder(null);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 60, 20));

        jButton4.setText("NOVO");
        jButton4.setBorder(null);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 50, 20));

        TbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME DO CURSO", "PREÇO DO CURSO", "CATEGORIA", "DURAÇÃO", "Nº DA SALA"
            }
        ));
        TbCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbCursos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 799, 140));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("NOME DO CURSO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        minimizar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        minimizar.setText("Minimizar");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        TxtCurso1.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        TxtCurso1.setForeground(new java.awt.Color(153, 153, 153));
        TxtCurso1.setText("Informe o Curso");
        TxtCurso1.setBorder(null);
        jPanel1.add(TxtCurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 251, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 250, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 250, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 250, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 250, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 250, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Cursos curso = new Cursos();
        Middle_BD_Cursos CursosBD = new Middle_BD_Cursos();
        MyConectBD Connection = new MyConectBD();
        curso.setNomeCurso(TxtCurso1.getText());
        curso.setPrecoCurso(Double.parseDouble(TxtPreco.getText()));
        curso.setCategoriaCurso(TxtCat.getText());
        curso.setTempoDurabilidade(TxtDurabi.getText());
        CursosBD.Inserir(curso);
        Adicionar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TbCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCursosMouseClicked
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) TbCursos.getModel();
        Cursos curso = new Cursos();
        Middle_BD_Cursos CursosBD = new Middle_BD_Cursos();
        int id = (int) TbCursos.getValueAt(TbCursos.getSelectedRow(), 0);
        curso.setIdcurso(id);
    }//GEN-LAST:event_TbCursosMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0) {
            setVisible(false);
        }

    }//GEN-LAST:event_SairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCursos_Erp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCursos_Erp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCursos_Erp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCursos_Erp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCursos_Erp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pesquisa;
    private javax.swing.JLabel Sair;
    private javax.swing.JTable TbCursos;
    private javax.swing.JTextField TxtCat;
    private javax.swing.JTextField TxtCurso1;
    private javax.swing.JTextField TxtDurabi;
    private javax.swing.JTextField TxtPreco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel minimizar;
    // End of variables declaration//GEN-END:variables
private void Adicionar() {
        Middle_BD_Cursos adicionador = new Middle_BD_Cursos();
        DefaultTableModel Tabledata = (DefaultTableModel) TbCursos.getModel();
        Tabledata.setNumRows(0);
        for (Cursos curso : adicionador.Listarcursos()) {
            Object[] receberDados = {
                curso.getIdcurso(),
                curso.getNomeCurso(),
                curso.getPrecoCurso(),
                curso.getCategoriaCurso(),
                curso.getTempoDurabilidade()
            };
            Tabledata.addRow(receberDados);
        }

    }

}
