/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Classes.Professores;
import Classes.Usuarios;
import Controller_Class_Entidades_Erp.Middle_BD_Professor;
import Controller_Class_Entidades_Erp.Middle_UsuarioBD;
import MysqlConectClasses.MyConectBD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class FrmUsrs extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsrs() {
        initComponents();
        this.setLocationRelativeTo(null);
        Adicionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        minimizar = new javax.swing.JLabel();
        sair = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nome Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Senha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        TxtNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtNome.setForeground(new java.awt.Color(204, 204, 204));
        TxtNome.setText("Nome do Usuario");
        TxtNome.setBorder(null);
        jPanel1.add(TxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 188, -1));

        TxtSenha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtSenha.setForeground(new java.awt.Color(204, 204, 204));
        TxtSenha.setText("Senha");
        TxtSenha.setBorder(null);
        jPanel1.add(TxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 188, -1));

        jButton1.setText("NOVO");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 40, 20));

        BtnSalvar.setText("SALVAR");
        BtnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, 20));

        jButton3.setText("ACTUALIZAR");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 90, 20));

        jButton4.setText("APAGAR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 190, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("USUÁRIOS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 30));

        TbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_USÁRIO", "NOME", "SENHA"
            }
        ));
        TbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbUser);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        minimizar.setText("Minimizar");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel2.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 60, -1));

        sair.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jPanel2.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 30, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("FAÇA DOS SEUS SISTEMAS DISTRIBUÍDOS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 400, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11.jpeg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 390, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        
        Usuarios usuarios = new Usuarios();
        MyConectBD Connection = new MyConectBD();
        Middle_UsuarioBD usuarioBD = new Middle_UsuarioBD();
        usuarios.setNome(TxtNome.getText());
        usuarios.setSenha(TxtSenha.getText());
        usuarioBD.Inserir(usuarios);
        Adicionar();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
           int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_sairMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
    this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void TbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbUserMouseClicked
          DefaultTableModel dtm = (DefaultTableModel) TbUser.getModel();
        Usuarios usuario = new Usuarios();
        Middle_UsuarioBD usuarioBD = new Middle_UsuarioBD();
        int id = (int) TbUser.getValueAt(TbUser.getSelectedRow(), 0);
       usuario.setId_usuario(id);
        Adicionar();
    }//GEN-LAST:event_TbUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsrs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTable TbUser;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel sair;
    // End of variables declaration//GEN-END:variables
private void Adicionar() {
        Middle_UsuarioBD adicionador = new Middle_UsuarioBD();
        DefaultTableModel Tabledata= (DefaultTableModel) TbUser.getModel();
        Tabledata.setNumRows(0);
        for (Usuarios usuarios : adicionador.ListarUsuarios()) {
       Object[] receberDados={
           usuarios.getId_usuario(),
           usuarios.getNome(),
           usuarios.getSenha(),
           
                 }; 
       Tabledata.addRow(receberDados);
        }
        
    }

}
