/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Armando Katito
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbFucio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LbProfessor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LbAlunos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LbAnalise = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LbCurso = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LbCargo = new javax.swing.JLabel();
        LbSalas = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11.jpeg"))); // NOI18N
        LbUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        LbUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbUserMouseMoved(evt);
            }
        });
        LbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbUserMouseExited(evt);
            }
        });
        jPanel1.add(LbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 300, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("     USUÁRIOS");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 110, 20));

        LbFucio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12.jpeg"))); // NOI18N
        LbFucio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        LbFucio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbFucioMouseMoved(evt);
            }
        });
        LbFucio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbFucioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbFucioMouseExited(evt);
            }
        });
        jPanel1.add(LbFucio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 170));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa.PNG"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, 30, 30));

        LbProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/13.jpg"))); // NOI18N
        LbProfessor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        LbProfessor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbProfessorMouseMoved(evt);
            }
        });
        LbProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbProfessorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbProfessorMouseExited(evt);
            }
        });
        jPanel1.add(LbProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 260, 170));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("      PROFESSORES");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 140, 20));

        LbAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/15.jpeg"))); // NOI18N
        LbAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        LbAlunos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbAlunosMouseMoved(evt);
            }
        });
        LbAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbAlunosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbAlunosMouseExited(evt);
            }
        });
        jPanel1.add(LbAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 270, 170));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("       ALUNOS");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 280, 140, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("   ANÁLISE  DE DADOS");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 510, 140, 20));

        LbAnalise.setForeground(new java.awt.Color(255, 0, 51));
        LbAnalise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/10.jpeg"))); // NOI18N
        LbAnalise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        LbAnalise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbAnaliseMouseMoved(evt);
            }
        });
        LbAnalise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbAnaliseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbAnaliseMouseExited(evt);
            }
        });
        jPanel1.add(LbAnalise, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 250, 170));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("          CURSOS");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 140, 20));

        LbCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.jpeg"))); // NOI18N
        LbCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        LbCurso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbCursoMouseMoved(evt);
            }
        });
        LbCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCursoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbCursoMouseExited(evt);
            }
        });
        jPanel1.add(LbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 300, 170));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("        CARGO");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 110, 20));

        LbCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/17.jpeg"))); // NOI18N
        LbCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        LbCargo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbCargoMouseMoved(evt);
            }
        });
        LbCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCargoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbCargoMouseExited(evt);
            }
        });
        jPanel1.add(LbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 320, 170));

        LbSalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.jpeg"))); // NOI18N
        LbSalas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        LbSalas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LbSalasMouseMoved(evt);
            }
        });
        LbSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSalasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbSalasMouseExited(evt);
            }
        });
        jPanel1.add(LbSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 300, 170));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("   SALAS DE AULAS");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 140, 20));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("  FUNCIONÁRIOS");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 120, 20));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("ÁREA DE  CRUED  DO SISTEMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 300, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 200, 20));

        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Pesquisar");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 200, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbFucioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbFucioMouseMoved
        // TODO add your handling code here:
        LbFucio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbFucioMouseMoved

    private void LbFucioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbFucioMouseExited
        // TODO add your handling code here:
        LbFucio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbFucioMouseExited

    private void LbUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbUserMouseMoved
        // TODO add your handling code here:
        LbUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbUserMouseMoved


    private void LbProfessorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProfessorMouseMoved
        // TODO add your handling code here:
        LbProfessor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbProfessorMouseMoved

    private void LbUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbUserMouseExited
        // TODO add your handling code here:
        LbUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbUserMouseExited

    private void LbProfessorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProfessorMouseExited
        // TODO add your handling code here:
        LbProfessor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbProfessorMouseExited

    private void LbAlunosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAlunosMouseMoved
        // TODO add your handling code here:
        LbAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbAlunosMouseMoved

    private void LbAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAlunosMouseExited
        // TODO add your handling code here:
        LbAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbAlunosMouseExited

    private void LbSalasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalasMouseMoved
        // TODO add your handling code here:
        LbSalas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbSalasMouseMoved

    private void LbSalasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalasMouseExited
        LbSalas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbSalasMouseExited

    private void LbCargoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCargoMouseMoved
        LbCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbCargoMouseMoved

    private void LbCargoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCargoMouseExited
        LbCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbCargoMouseExited

    private void LbCursoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCursoMouseMoved
        LbCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbCursoMouseMoved

    private void LbCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCursoMouseExited
        LbCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbCursoMouseExited

    private void LbAnaliseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAnaliseMouseMoved
        LbAnalise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_LbAnaliseMouseMoved

    private void LbAnaliseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAnaliseMouseExited
        LbAnalise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_LbAnaliseMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void LbFucioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbFucioMouseClicked

        Cadastrar_Funcionarios funcionario = new Cadastrar_Funcionarios();
        funcionario.setVisible(true);
    }//GEN-LAST:event_LbFucioMouseClicked

    private void LbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbUserMouseClicked
        FrmUsrs usuarios = new FrmUsrs();
        usuarios.setVisible(true);
    }//GEN-LAST:event_LbUserMouseClicked

    private void LbCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCargoMouseClicked
        Cargo cargo = new Cargo();
        cargo.setVisible(true);
    }//GEN-LAST:event_LbCargoMouseClicked

    private void LbCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCursoMouseClicked
        FrmCursos_Erp curso = new FrmCursos_Erp();
        curso.setVisible(true);
    }//GEN-LAST:event_LbCursoMouseClicked

    private void LbAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAlunosMouseClicked
      Frm_Estudante estudante = new Frm_Estudante();
      estudante.setVisible(true);
    }//GEN-LAST:event_LbAlunosMouseClicked

    private void LbProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProfessorMouseClicked
        Frm_Professor professor = new Frm_Professor();
        professor.setVisible(true);
    }//GEN-LAST:event_LbProfessorMouseClicked

    private void LbAnaliseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAnaliseMouseClicked
    ManegerArea analit = new ManegerArea();
    analit.setVisible(true);
    }//GEN-LAST:event_LbAnaliseMouseClicked

    private void LbSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalasMouseClicked
        SalasFrm salas = new SalasFrm();
        salas.setVisible(true);
    }//GEN-LAST:event_LbSalasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbAlunos;
    private javax.swing.JLabel LbAnalise;
    private javax.swing.JLabel LbCargo;
    private javax.swing.JLabel LbCurso;
    private javax.swing.JLabel LbFucio;
    private javax.swing.JLabel LbProfessor;
    private javax.swing.JLabel LbSalas;
    private javax.swing.JLabel LbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
