/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import AppPackage.AnimationClass;
import Classes.Analitycs;
import Classes.Cursos;
import Classes.Estudantes;
import Classes.Funcionarios;
import Classes.Professores;
import Classes.Usuarios;
import Controller_Class_Entidades_Erp.Middle_BD_Cursos;
import javax.swing.JOptionPane;
import Controller_Class_Entidades_Erp.Middle_BD_Data_Analitycs;
import Controller_Class_Entidades_Erp.Middle_BD_Estudante;
import Controller_Class_Entidades_Erp.Middle_BD_Funcionario;
import Controller_Class_Entidades_Erp.Middle_BD_Professor;
import Controller_Class_Entidades_Erp.Middle_UsuarioBD;
import MysqlConectClasses.MyConectBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class ManegerArea extends javax.swing.JFrame {

    /**
     * Creates new form ManegerArea
     */
    public ManegerArea() {
        initComponents();
        this.setLocationRelativeTo(null);    
        Adicionarfunc();
        AdicionarAlunos();
        Adicionaruser();
        AdicionarProf();
        AdicionarCurso();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbData3 = new javax.swing.JLabel();
        LbData = new javax.swing.JLabel();
        LbFuncionarios = new javax.swing.JLabel();
        Lbusers = new javax.swing.JLabel();
        LbProfessor = new javax.swing.JLabel();
        LbEstudantes = new javax.swing.JLabel();
        LbManager = new javax.swing.JLabel();
        LbCursos1 = new javax.swing.JLabel();
        LbData1 = new javax.swing.JLabel();
        LbData2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbTotal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbFuncionario = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbUsuario = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tbprfesspr = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TbAlunos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TbCursos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        LbMinimi = new javax.swing.JLabel();
        LbExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashaboard");
        setBackground(new java.awt.Color(51, 204, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbData3.setBackground(new java.awt.Color(255, 255, 255));
        LbData3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 19)); // NOI18N
        LbData3.setForeground(new java.awt.Color(255, 255, 255));
        LbData3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globe.png"))); // NOI18N
        LbData3.setText("Previsão de Metas");
        jPanel1.add(LbData3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 180, 30));

        LbData.setBackground(new java.awt.Color(255, 255, 255));
        LbData.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LbData.setForeground(new java.awt.Color(255, 255, 255));
        LbData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/data.png"))); // NOI18N
        LbData.setText("Análise de Dados");
        LbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbDataMouseClicked(evt);
            }
        });
        jPanel1.add(LbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 310, 30));

        LbFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        LbFuncionarios.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        LbFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        LbFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/func.png"))); // NOI18N
        LbFuncionarios.setText("FUNCIONÁRIOS");
        jPanel1.add(LbFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 30));

        Lbusers.setBackground(new java.awt.Color(255, 255, 255));
        Lbusers.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        Lbusers.setForeground(new java.awt.Color(255, 255, 255));
        Lbusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-avatar-9.png"))); // NOI18N
        Lbusers.setText("USUÁRIOS");
        jPanel1.add(Lbusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 30));

        LbProfessor.setBackground(new java.awt.Color(255, 255, 255));
        LbProfessor.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        LbProfessor.setForeground(new java.awt.Color(255, 255, 255));
        LbProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tch.png"))); // NOI18N
        LbProfessor.setText("PROFESSORES");
        jPanel1.add(LbProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        LbEstudantes.setBackground(new java.awt.Color(255, 255, 255));
        LbEstudantes.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        LbEstudantes.setForeground(new java.awt.Color(255, 255, 255));
        LbEstudantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aluno].png"))); // NOI18N
        LbEstudantes.setText("ESTUDANTES");
        jPanel1.add(LbEstudantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, 20));

        LbManager.setBackground(new java.awt.Color(255, 255, 255));
        LbManager.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LbManager.setForeground(new java.awt.Color(255, 255, 255));
        LbManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastrar.png"))); // NOI18N
        LbManager.setText("PAINEL DE GESTÃO");
        LbManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbManagerMouseClicked(evt);
            }
        });
        jPanel1.add(LbManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, 30));

        LbCursos1.setBackground(new java.awt.Color(255, 255, 255));
        LbCursos1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        LbCursos1.setForeground(new java.awt.Color(255, 255, 255));
        LbCursos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/curso.png"))); // NOI18N
        LbCursos1.setText("CURSOS");
        jPanel1.add(LbCursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 20));

        LbData1.setBackground(new java.awt.Color(255, 255, 255));
        LbData1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 19)); // NOI18N
        LbData1.setForeground(new java.awt.Color(255, 255, 255));
        LbData1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document.png"))); // NOI18N
        LbData1.setText("Cursos Mais frequentados");
        jPanel1.add(LbData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 240, 30));

        LbData2.setBackground(new java.awt.Color(255, 255, 255));
        LbData2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 19)); // NOI18N
        LbData2.setForeground(new java.awt.Color(255, 255, 255));
        LbData2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/area_gesta.png"))); // NOI18N
        LbData2.setText("Lucros por curso");
        jPanel1.add(LbData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbTotal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TbTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total de Funcionários", "Total de Usuários", "Total de  Professores", "Total de Estudantes", "Total de Cursos"
            }
        ));
        TbTotal.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TbTotal);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 880, 160));

        TbFuncionario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TbFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionário"
            }
        ));
        TbFuncionario.setGridColor(new java.awt.Color(255, 255, 255));
        TbFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TbFuncionario);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 190, 160));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("CONTROLE DAS ENTIDADES DO SISTEMA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 480, 20));

        TbUsuario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario"
            }
        ));
        TbUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        TbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TbUsuario);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 160));

        Tbprfesspr.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Tbprfesspr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Professor"
            }
        ));
        Tbprfesspr.setGridColor(new java.awt.Color(255, 255, 255));
        Tbprfesspr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbprfessprMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tbprfesspr);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, 160));

        TbAlunos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TbAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alunos"
            }
        ));
        TbAlunos.setGridColor(new java.awt.Color(255, 255, 255));
        TbAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbAlunosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TbAlunos);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 170, 160));

        TbCursos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cursos"
            }
        ));
        TbCursos.setGridColor(new java.awt.Color(255, 255, 255));
        TbCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbCursosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TbCursos);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 160, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 880, 500));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jTextField1.setBackground(new java.awt.Color(0, 102, 204));
        jTextField1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Pesquisar...");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/func.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa.PNG"))); // NOI18N

        jTextField3.setBackground(new java.awt.Color(0, 102, 204));
        jTextField3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Armando Katito");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        LbMinimi.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        LbMinimi.setForeground(new java.awt.Color(255, 255, 255));
        LbMinimi.setText("Minimizar");
        LbMinimi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbMinimiMouseClicked(evt);
            }
        });

        LbExit.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        LbExit.setForeground(new java.awt.Color(255, 255, 255));
        LbExit.setText("Sair");
        LbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(LbMinimi, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbMinimi)
                        .addComponent(LbExit))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 890, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbManagerMouseClicked
        AnimationClass func = new AnimationClass();
        func.jLabelXRight(-250, 10, 10, 5, LbFuncionarios);

        AnimationClass func1 = new AnimationClass();
        func1.jLabelXLeft(10, -250, 10, 5, LbFuncionarios);

        AnimationClass estudante = new AnimationClass();
        estudante.jLabelXRight(-250, 10, 10, 5, LbEstudantes);

        AnimationClass estudante1 = new AnimationClass();
        estudante1.jLabelXLeft(10, -250, 10, 5, LbEstudantes);

        AnimationClass curso = new AnimationClass();
        curso.jLabelXRight(-250, 10, 10, 5, LbCursos1);

        AnimationClass curso1 = new AnimationClass();
        curso1.jLabelXLeft(10, -250, 10, 5, LbCursos1);

        AnimationClass user = new AnimationClass();
        curso.jLabelXRight(-250, 10, 10, 5, Lbusers);

        AnimationClass user1 = new AnimationClass();
        user1.jLabelXLeft(10, -250, 10, 5, Lbusers);

        AnimationClass prof = new AnimationClass();
        prof.jLabelXRight(-250, 10, 10, 5, LbProfessor);

        AnimationClass prof1 = new AnimationClass();
        prof1.jLabelXLeft(10, -250, 10, 5, LbProfessor);
    }//GEN-LAST:event_LbManagerMouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void LbMinimiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbMinimiMouseClicked
        // TODO add your handling code here:
        this.setState(ManegerArea.ICONIFIED);
    }//GEN-LAST:event_LbMinimiMouseClicked

    private void LbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbExitMouseClicked
        // TODO add your handling code here:
        int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0) {

            setVisible(false);
        }
    }//GEN-LAST:event_LbExitMouseClicked

    private void TbFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbFuncionarioMouseClicked
      // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) TbFuncionario.getModel();
        Funcionarios funcionario = new Funcionarios();
        Middle_BD_Data_Analitycs funcionarioBD = new Middle_BD_Data_Analitycs();
        int id = (int) TbFuncionario.getValueAt(TbFuncionario.getSelectedRow(), 0);
        funcionario.setId_funcionario(id);
        // funcionarioBD.
        Adicionarfunc();

    }//GEN-LAST:event_TbFuncionarioMouseClicked

    private void TbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbUsuarioMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) TbUsuario.getModel();
        Usuarios usuario = new Usuarios();
        Middle_BD_Data_Analitycs usuarioBD = new Middle_BD_Data_Analitycs();
        int id = (int) TbUsuario.getValueAt(TbUsuario.getSelectedRow(), 0);
       usuario.setId_usuario(id);
        Adicionaruser();
    }//GEN-LAST:event_TbUsuarioMouseClicked

    private void TbprfessprMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbprfessprMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) Tbprfesspr.getModel();
        Professores professor = new Professores();
        Middle_BD_Data_Analitycs professorBD = new Middle_BD_Data_Analitycs();
        int id = (int) Tbprfesspr.getValueAt(Tbprfesspr.getSelectedRow(), 0);
        professor.setId_professor(id);
        AdicionarProf();
    }//GEN-LAST:event_TbprfessprMouseClicked

    private void TbAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbAlunosMouseClicked
      DefaultTableModel dtm = (DefaultTableModel)TbAlunos.getModel();
         Estudantes estudante = new Estudantes();
        Middle_BD_Data_Analitycs estudanteBD = new Middle_BD_Data_Analitycs();
        int id = (int)TbAlunos.getValueAt(TbAlunos.getSelectedRow(),0);
        estudante.setIdestudante(id);
        AdicionarAlunos();
    }//GEN-LAST:event_TbAlunosMouseClicked

    private void TbCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCursosMouseClicked
     DefaultTableModel dtm = (DefaultTableModel)TbCursos.getModel();
         Cursos curso = new Cursos();
        Middle_BD_Data_Analitycs CursosBD = new Middle_BD_Data_Analitycs();
        int id = (int)TbCursos.getValueAt(TbCursos.getSelectedRow(),0);
        curso.setIdcurso(id);
        AdicionarCurso();
    }//GEN-LAST:event_TbCursosMouseClicked

    private void LbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbDataMouseClicked
        // TODO add your handling code here        
         AnimationClass data = new AnimationClass();
        data.jLabelXRight(-250, 10, 10, 5, LbData1);

        AnimationClass data1 = new AnimationClass();
        data1.jLabelXLeft(10, -250, 10, 5, LbData1);

        AnimationClass dat = new AnimationClass();
        dat.jLabelXRight(-250, 10, 10, 5, LbData2);

        AnimationClass dat1 = new AnimationClass();
        dat1.jLabelXLeft(10, -250, 10, 5, LbData2);

        AnimationClass dataanali = new AnimationClass();
        dataanali.jLabelXRight(-250, 10, 10, 5, LbData3);

        AnimationClass dataanali1 = new AnimationClass();
        dataanali1.jLabelXLeft(10, -250, 10, 5, LbData3);
    }//GEN-LAST:event_LbDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManegerArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManegerArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManegerArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManegerArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManegerArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbCursos1;
    private javax.swing.JLabel LbData;
    private javax.swing.JLabel LbData1;
    private javax.swing.JLabel LbData2;
    private javax.swing.JLabel LbData3;
    private javax.swing.JLabel LbEstudantes;
    private javax.swing.JLabel LbExit;
    private javax.swing.JLabel LbFuncionarios;
    private javax.swing.JLabel LbManager;
    private javax.swing.JLabel LbMinimi;
    private javax.swing.JLabel LbProfessor;
    private javax.swing.JLabel Lbusers;
    private javax.swing.JTable TbAlunos;
    private javax.swing.JTable TbCursos;
    private javax.swing.JTable TbFuncionario;
    private javax.swing.JTable TbTotal;
    private javax.swing.JTable TbUsuario;
    private javax.swing.JTable Tbprfesspr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

      private void Adicionarfunc() {
        Middle_BD_Data_Analitycs adicionador = new Middle_BD_Data_Analitycs();
        DefaultTableModel Tabledata = (DefaultTableModel) TbFuncionario.getModel();
        Tabledata.setNumRows(0);
        for (Funcionarios funcionario : adicionador.Listarfuncion()) {
            Object[] receberDados = {
                 funcionario.getNome_funcionario(),};
            Tabledata.addRow(receberDados);
        }

    }
    private void AdicionarAlunos() {
        Middle_BD_Data_Analitycs adicionador = new Middle_BD_Data_Analitycs();
        DefaultTableModel Tabledata= (DefaultTableModel) TbAlunos.getModel();
        Tabledata.setNumRows(0);
        for (Estudantes estudante : adicionador.ListarEstudante()) {
       Object[] receberDados={
          estudante.getNomeEstudante(),
       }; 
       Tabledata.addRow(receberDados);
        }
        
    }
    
   private void AdicionarProf() {
        Middle_BD_Data_Analitycs adicionador = new Middle_BD_Data_Analitycs();
        DefaultTableModel Tabledata = (DefaultTableModel) Tbprfesspr.getModel();
        Tabledata.setNumRows(0);
        for (Professores professor : adicionador.ListarProfessor()) {
            Object[] receberDados = {
            professor.getNome_professor(),
            };
            Tabledata.addRow(receberDados);
        }

    }
   private void Adicionaruser() {
        Middle_BD_Data_Analitycs adicionador = new Middle_BD_Data_Analitycs();
        DefaultTableModel Tabledata= (DefaultTableModel) TbUsuario.getModel();
        Tabledata.setNumRows(0);
        for (Usuarios usuarios : adicionador.ListarUsuarios()) {
       Object[] receberDados={
        usuarios.getNome(),
                 }; 
       Tabledata.addRow(receberDados);
        }
        
    }
    
   private void AdicionarCurso() {
         Middle_BD_Data_Analitycs adicionador = new Middle_BD_Data_Analitycs();
        DefaultTableModel Tabledata= (DefaultTableModel) TbCursos.getModel();
        Tabledata.setNumRows(0);
        for (Cursos curso : adicionador.Listarcursos()) {
       Object[] receberDados={
           curso.getNomeCurso(),
       }; 
       Tabledata.addRow(receberDados);
        }
        
    }
    
    
    
   /*
 * private void Adicionar() {
        Middle_BD_Data_Analitycs adicionador = new Middle_BD_Data_Analitycs();
        DefaultTableModel Tabledata = (DefaultTableModel) TbFuncionario.getModel();
        Tabledata.setNumRows(0);
        for (Analitycs analise : adicionador.ListarEntidades()) {
            Object[] receberDados = {
                analise.getUsuarios(),
                analise.getProfessor(),
                analise.getEstudantes(),
                analise.getCursos(),
                analise.getFuncionarios(),};
            Tabledata.addRow(receberDados);
        }

    }
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    
       
}
