/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.SalasAulas;
import Controller_Class_Entidades_Erp.Middle_BD_Salas;
import MysqlConectClasses.MyConectBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando Katito
 */
public class SalasFrm extends javax.swing.JFrame {

    /**
     * Creates new form SalasFrm
     */
    public SalasFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        Adicionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbSala = new javax.swing.JTable();
        BtnApagar = new javax.swing.JButton();
        TxtNumber = new javax.swing.JTextField();
        TxtCurso = new javax.swing.JTextField();
        TxtCapacidade = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        BtnDel = new javax.swing.JButton();
        BtnNew = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        BtnUpdt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Numero da Sala");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Curso da Sala");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Capacidade");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, -1));

        TbSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id da Sala", "Number", "Nome do curso", "Capacidade"
            }
        ));
        TbSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbSalaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbSala);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 702, 194));

        BtnApagar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BtnApagar.setBorder(null);
        jPanel1.add(BtnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 189, -1, -1));

        TxtNumber.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        TxtNumber.setForeground(new java.awt.Color(102, 102, 102));
        TxtNumber.setText("Sala Number");
        TxtNumber.setBorder(null);
        jPanel1.add(TxtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, -1));

        TxtCurso.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        TxtCurso.setForeground(new java.awt.Color(102, 102, 102));
        TxtCurso.setText("Informar o Curso");
        TxtCurso.setBorder(null);
        TxtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCursoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 110, 20));

        TxtCapacidade.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        TxtCapacidade.setForeground(new java.awt.Color(102, 102, 102));
        TxtCapacidade.setText("Capacidade");
        TxtCapacidade.setBorder(null);
        TxtCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCapacidadeActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 201, 15));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 201, 15));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 201, 15));

        jTextField4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jTextField4.setText("Pesquisar Cursos");
        jTextField4.setBorder(null);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 122, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 180, 15));

        BtnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnDel.setText("APAGAR");
        BtnDel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(BtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, 20));

        BtnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNew.setText("NOVO");
        BtnNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(BtnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 20));

        BtnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSave.setText("SALVAR");
        BtnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, 20));

        BtnUpdt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnUpdt.setText("ACTUALIZAR");
        BtnUpdt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(BtnUpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Sair");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, -1));

        minimizar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        minimizar.setText("minimizar");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 10, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCursoActionPerformed

    private void TxtCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCapacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCapacidadeActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        SalasAulas sala = new SalasAulas();
        MyConectBD Connection = new MyConectBD();
        Middle_BD_Salas SalaBD = new Middle_BD_Salas();
        sala.setNumero_sala(Integer.parseInt(TxtNumber.getText()));
        sala.setCurso_sala(TxtCurso.getText());
        sala.setCapacidade_sala(Integer.parseInt(TxtCapacidade.getText()));
        SalaBD.InserirSalas(sala);
        Adicionar();
        

    }//GEN-LAST:event_BtnSaveActionPerformed

    private void TbSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbSalaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) TbSala.getModel();
        SalasAulas funcionario = new SalasAulas();
        Middle_BD_Salas funcionarioBD = new Middle_BD_Salas();
        int id = (int) TbSala.getValueAt(TbSala.getSelectedRow(), 0);
        funcionario.setId_sala(id);
    }//GEN-LAST:event_TbSalaMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        // TODO add your handling code here:
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        int dialog = JOptionPane.YES_NO_OPTION;
        int resul = JOptionPane.showConfirmDialog(null, "Deseja sair?", "exit", dialog);
        if (resul == 0) {
            setVisible(false);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalasFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApagar;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnNew;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdt;
    private javax.swing.JTable TbSala;
    private javax.swing.JTextField TxtCapacidade;
    private javax.swing.JTextField TxtCurso;
    private javax.swing.JTextField TxtNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel minimizar;
    // End of variables declaration//GEN-END:variables

    private void Adicionar() {
        Middle_BD_Salas adicionador = new Middle_BD_Salas();
        DefaultTableModel Tabledata = (DefaultTableModel) TbSala.getModel();
        Tabledata.setNumRows(0);
        for (SalasAulas salas : adicionador.ListarSalas()) {
            Object[] receberDados = {
                salas.getId_sala(),
                salas.getNumero_sala(),
                salas.getCurso_sala(),
                salas.getCapacidade_sala()
            };            
            Tabledata.addRow(receberDados);
        }
        
    }
    
}
